runtime: nodejs
env: flex
health_check:
  enable_health_check: False
# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
network:
  session_affinity: true
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10